# Data sources

UCDP Georeferenced Event Dataset (GED) Global version 19.1 from UCDP Dataset (https://ucdp.uu.se/downloads/index.html#ged_global){target="_blank"} is used in our project, this dataset covers "individual events of organized violence (phenomena of lethal violence occurring at a given time and place)" in a world-wide perspective [[source](https://ucdp.uu.se/downloads/index.html#ged_global){target="_blank"}].

There are 152,616 records in the dataset, and each record in the dataset is an event of a specific conflict. An event of a conflict is defined as "An incident where armed force was used by an organized actor against another organized actor, or against civilians." [[source](https://ucdp.uu.se/downloads/ged/ged191.pdf){target="_blank"}]. 

To avoid potential ambiguities, "conflict event" is used in our project to express the term "event" in the original terminology. This dataset contains data of armed conflict events from a world-wide perspective, from 1989 to 2018; includes the time, geographic location, type, casualties, and other information regarding the conflict event. 

There are a total of 43 variables in the original dataset, and for the full definitions and explanations of variables, please refer to the dataset's codebook [[source](https://ucdp.uu.se/downloads/ged/ged191.pdf){target="_blank"}]. However, there are some repeated variables. For example, there are several variables to represent the geo-location of one conflict event, they refer to the same location, but in different formats to suit different geographic databases. In our study, for the location variables, we are only interested in the vanilla `latitude` and `longitude` variables.

For the propose of analyzing conflicts' data patterns in this project, we mostly focus on a subset of variables; the following are the variables and their explanations. Explanations are referred from the codebook of the dataset [[source](https://ucdp.uu.se/downloads/ged/ged191.pdf){target="_blank"}].

```{r echo= FALSE, results= 'asis'}
library(knitr)
var_ex = data.frame(
  Variable = c("id",
               "date_start",
               "date_end",
               "year",
               "type_of_violence",
               "side_a/side_b",
               "longitude/latitude",
               "country",
               "region",
               "death_*",
               "best",
               "high/low"),
  Explanation = c("An unique ID identifying a conflict event",
                "The earliest possible date when the conflict event has taken place",
                "The last possible date when the conflict event has taken place",
                "The year of the conflict event",
                "1: state-based conflict (involved with a government of a state or any opposition organization or alliance of organizations); 2: non-state conflict (between organized armed groups); 3: one-sided violence (against civilians)",
                "The name of the two sides",
                "Best estimated or the actual location of the conflict event takes place",
                "Name of the country of the conflict event takes place",
                "Africa, Americas, Asia, Europe, Middle East",
                "Best estimate of fatalities for the specific group",
                "Best estimate of fatalities resulting from the conflict event",
                "The highest/lowest estimation of the total fatalities"))
kable(var_ex)
```

One point that needs to be noticed of this dataset is "[the] [d]ata for Syria is not included in the current version" ([source](https://ucdp.uu.se/downloads/ged/ged191.pdf){target="_blank"}, p. 3). And as mentioned in the dataset's [codebook](https://ucdp.uu.se/downloads/ged/ged191.pdf){target="_blank"}, "the data collection for Syria is ongoing but the final product is not releasable at this time with the same level of consistency and clarity as other UCDP GED data." Thus, the actual total number of conflict events and deaths in recent years should be larger than the records in the dataset.