# Conclusion

As we went over all proposed questions related to the exploration of the dataset, we acquired a lot of interesting findings and verify our finding by corresponding historical facts. Although we analyzed distribution of death caused by conflicts, relataion between conflict and time, pattern between geographical location and type of violence, there still exists some aspects of analysis, that may lead to meaningful and inspirational findings. 

In our analysis, we have not analyzed the relation between death and type of violence. As we all know, given different type of violence, the resulted dealth of each type of violence could be significantly different. If we can dig this question into a deeper level, we can get some interesting findings related to each different type of violence. For instance, based on our common sense, because one-side conflict is the deliberate use of armed force by the government of a state or by a formally organised group against civilians, one-side conflict may cause more death of innocent civilians compared with other two types of violence. To be more specific, based on that, we can test our hypothesis by checking the average death of civilians caused by each type of violence. Then, we can create a plot to see the difference among them.

Moreover, during the exploration of the dataset, we mainly focused multiple conflict through time, except for some briefly explaination to representative patterns related to one specific conflict. In the future, we can choose one specific event as our main analysis object and focus on that single event to exlpore. One possiblity is to choose a conflict which last for a long time, such as War in Afghanistan, because long-term conflict event means that we have more room to perform analysis.

In addition, although we have analyzed relation between conflict and time, we will perform time-series analysis based on month, or day if we have time to do this in the future. When we split the data based on month, in time-series, we can see the trend of number of conflicts happened based on month/day. Meanwhile, we may figure out which month or day has the largest number of conflicts in a year, which seems to be very interesting.

Unfortunately, our dataset does not include data for Syria because the data collection for Syria is ongoing and the final product is not released yet. In the future, if data for Syria can be added to the dataset in future, we will be able to perform a more complete and reliable analysis based on that new dataset because Syria Civil War is the most current conflict event.