--- 
title: "Analysis on World Armed Conflicts Data"
author: "Yitao Liu (yl4343), Boyu Liu (bl2788), Yiyang Sun (ys3284)"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
github-repo: tonyytliu/EDAV_Project
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE, fig.align='center')
library(dplyr)
library(here)
library(ggplot2)
library(ggpubr)
library(mapproj)
library(scales)
library(naniar)
library(extracat)
library(ggmosaic)
```

# Introduction

More than 70 years have passed after the end of World War II, but the armed conflicts still seem to wreak havoc around the world, and military activities continued to threaten the peace and stability of the world. "Are we living in a peaceful era?" "Is the world becoming more and more peaceful?" "How many people died because of these conflicts?" Many questions would come out if thinking about the world we live in.

To have a more comprehensive view of the peace and conflicts, researchers from the Department of Peace and Conflict Research, Uppsala University, have collected and organized data of armed conflicts in the past decades ([link](https://ucdp.uu.se/downloads/index.html#ged_global){target="_blank"} to their website). This dataset includes the conflict data from 1989 to 2018, which gives us opportunities to further analysis the armed conflicts around the world. (Note that  "Conflict" in this project means "armed conflict," which consists of "incident[s] where  armed force was used by an organized actor against another organized actor, or against civilians." [[source]](https://ucdp.uu.se/downloads/ged/ged191.pdf){target="_blank"}
)

First, we would like to look at some general questions regarding world conflict, "what is the most fierce conflict in the past 30 years?" "What is the distribution of fatalities caused by conflicts?" "How many civilians died in those conflicts?". Furthermore, we want to investigate the conflicts through time and geographic perspectives, "is the changing of the time change our answers to the above questions?" "Is there any patterns for type of violence in different regions?"

In the following chapters, we will show the information and data, which can give some understandings of the above questions. We hope our analysis in this project will provide you more insights into the broader question of the world's peace and conflicts.

The GitHub repo for our project is [here](https://github.com/tonyytliu/world_conflict_data){target="_blank"}, or copy the url: https://github.com/tonyytliu/world_conflict_data. Code please refer to the `.Rmd` files.